<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            margin: 20px;
        }

        h2 {
            text-align: center;
            color: #005BAC;
            margin-bottom: 5px;
        }

        .sub {
            text-align: center;
            color: #555;
            margin-bottom: 15px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th {
            background: #005BAC;
            color: white;
            padding: 8px;
            border: 1px solid #ccc;
        }

        td {
            padding: 7px;
            border: 1px solid #ccc;
        }

        tr:nth-child(even) {
            background: #f8fafc;
        }

        .center {
            text-align: center;
        }

        .footer {
            margin-top: 15px;
            text-align: right;
            font-size: 10px;
            color: #777;
        }
    </style>
</head>

<body>

    <h2>PT WIKA BETON</h2>

    <div class="sub">
        Laporan Histori Transaksi Material<br>
        Tanggal Cetak: <?= date('d-m-Y H:i') ?>
    </div>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Tanggal</th>
                <th>Material</th>
                <th>Jenis</th>
                <th>Jumlah</th>
            </tr>
        </thead>

        <tbody>

            <?php $no = 1;
            foreach ($transaksi as $t): ?>

                <tr>
                    <td class="center"><?= $no++ ?></td>
                    <td><?= date('d-m-Y H:i', strtotime($t['tanggal'])) ?></td>
                    <td><?= $t['nama_material'] ?></td>
                    <td class="center"><?= strtoupper($t['jenis']) ?></td>
                    <td class="center"><?= $t['jumlah'] ?></td>
                </tr>

            <?php endforeach; ?>

        </tbody>
    </table>

    <div class="footer">
        Generated by Sistem Gudang PT WIKA Beton
    </div>

</body>

</html>